
connector:
  type: activate.scanners.alchemy.AlchemyScanner
  options:
    # The database URL of the source system to scan
    # https://docs.sqlalchemy.org/en/20/core/engines.html
    database_url: "sqlite:///../databases/chinook.db"

  # Future types
  # type: airtable: https://airtable.com/developers/web/api/list-bases
  # type: excel
  # type: snowflake? If we don't connect with sqlalchemy

# The name for the system to scan - this will not over ride contents within Aristotle
# Is this required? Yes - on the first pass at least
name: "Chinook Database"

registry:
  url: http://127.0.0.1:8000/
  api_token: 54e9eff1f7dbcb50b23bac8d22937b478629c556
  pipeline: 622e2784-4add-11ef-bcce-0242ac110007

scan-options:
  # 
  object_types:
    # - schemas
    - tables
    - columns
    # - views

  # list of tables to include?
  # include: []

  # A list of tables (or table like objects to exclude from scanning)?
  # exclude: []