
connector:
  type: activate.scanners.alchemy.AlchemyScanner
  options:
    # The database URL of the source system to scan
    # https://docs.sqlalchemy.org/en/20/core/engines.html
    database_url: "sqlite:///../databases/chinook.db"

  # Future types
  # type: airtable: https://airtable.com/developers/web/api/list-bases
  # type: excel
  # type: snowflake? If we don't connect with sqlalchemy

# The name for the system to scan - this will not over ride contents within Aristotle
# Is this required? Yes - on the first pass at least
name: "Chinook Database"

registry:
  url: https://staging.koala.aristotle.ninja/
  api_token: e6b6056da75fac5ced62e5dbd3ba5237e1893d05
  pipeline: 72ee6624-23c2-11f0-b28d-0a58a9feac02

scan-options:
  # 
  object_types:
    # - schemas
    - tables
    - columns
    # - views

  # list of tables to include?
  # include: []

  # A list of tables (or table like objects to exclude from scanning)?
  # exclude: []