
connector:
  type: activate.scanners.ckan.CKANScanner
  options:
    # The database URL of the source system to scan
    # https://docs.sqlalchemy.org/en/20/core/engines.html
    ckan_url: "https://discover.data.vic.gov.au/"
    mapping:
      dataset:
        # Map CKAN fields to Aristotle fields
        name: title
        definition: notes
        rights: 
          type: concat
          separator: ""
          values:
            - type: string
              value: "<a href='"
            - type: field
              field: license_url
            - type: string
              value: "'>"
            - type: field
              field: license_title
            - type: string
              value: "</a>"
        release_date:
          type: field
          field: date_created_data_asset
        contact_point: 
          type: field
          field: maintainer_email
          default: ""
          on_null: "set_default"
        frequency: 
          type: field
          field: update_frequency
        updated_date:
          type: parse_date
          field: modified
          format: "%Y-%m-%d"
        landing_page: 
          type: concat
          separator: ""
          values:
            - type: string
              value: https://discover.data.vic.gov.au/data/
            - type: field
              field: id

    search:
      # Optional search parameters to filter datasets from CKAN
      # See https://docs.ckan.org/en/2.9/api/#ckan.logic.action.get.package_search
      # q: "organization:pacific-data"
      rows: 50 # Number of datasets to retrieve per request
      fq: "organization:department-of-education"
      sort: metadata_modified desc

# The name for the system to scan - this will not over ride contents within Aristotle
# Is this required? Yes - on the first pass at least
name: "CKAN Test"

registry:
  url: https://vic-edu-evaluation.aristotlecloud.io/
  api_token: 6d965d6b24c1dddd0c0a08e51e67c5c8b7a9a3e4
  pipeline: 2d32c2c8-92c2-11f0-8a82-0a58a9feac02

scan-options:
  # 
  object_types:
    # - schemas
    - tables
    - columns
    # - views

  # list of tables to include?
  # include: []


  # A list of tables (or table like objects to exclude from scanning)?
  # exclude: []