
connector:
  type: activate.scanners.dotstat.DotStatScanner
  options:
    dotstat_api_url: "https://data-sdmx-disseminate.sbs.gov.ws"
    dotstat_url: https://data.statsfiji.gov.fj/
    # dotstat_api_url: "https://stats-nsi-stable.pacificdata.org"
    # dotstat_url: "https://stats.pacificdata.org"


# The name for the system to scan - this will not over ride contents within Aristotle
# Is this required? Yes - on the first pass at least
name: "CKAN Test"

registry:
  url: https://spc.aristotlecloud.io/
  api_token: d2748e6174ce37791ac4e683b5ececc2f556e98c
  pipeline: c02c9756-8ecc-11f0-a406-0a58a9feac02

scan-options:
  # 
  object_types:
    # - schemas
    - tables
    - columns
    # - views

  # list of tables to include?
  # include: []


  # A list of tables (or table like objects to exclude from scanning)?
  # exclude: []